- hosts: all
  vars:
    galaxy_server_dir: /opt/galaxy/server
    galaxy_vcs: git
#    galaxy_config_dir: /opt/galaxy/config
#    galaxy_mutable_config_dir: /var/opt/galaxy/config
#    galaxy_mutable_data_dir: /var/opt/galaxy/data
#    galaxy_repo: https://bitbucket.org/galaxy/galaxy-central/
#    galaxy_repo: https://github.com/galaxyproject/galaxy
    galaxy_changeset_id: release_15.10
  pre_tasks:
    - name: Install Debian prerequisites
      apt: pkg={{ item }} state=installed
      sudo: yes
      when: ansible_os_family == 'Debian'
      with_items:
        - git
        - python-virtualenv
    - name: Install RedHat prerequisites
      yum: pkg={{ item }} state=installed
      sudo: yes
      when: ansible_os_family == 'RedHat'
      with_items:
        - git
        - python-virtualenv
  roles:
    - role: ../ansible-galaxy
      sudo: yes
