# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: admin
galaxy_instance: http://127.0.0.1:8080/
tools:
- name: camera_combinexsannos
  owner: mmonsoor
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: camera_annotate
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: xcms_summary
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: xcms_fillpeaks
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: xcms_retcor
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: xcms_group
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: xcms_xcmsset
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: hca
  owner: lecorguille
  tool_panel_section_id: 'LCMS-annotation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
- name: anova
  owner: lecorguille
  tool_panel_section_id: 'LCMS-annotation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
